# Generated by Django 5.0 on 2026-04-10 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userstatus_block_friendrequest_friendship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('color', models.CharField(choices=[('#4CAF50', '#4CAF50'), ('#2196F3', '#2196F3'), ('#9C27B0', '#9C27B0'), ('#FF5722', '#FF5722'), ('#F44336', '#F44336'), ('#FFC107', '#FFC107'), ('#00BCD4', '#00BCD4'), ('#8BC34A', '#8BC34A'), ('#3F51B5', '#3F51B5'), ('#E91E63', '#E91E63'), ('#795548', '#795548'), ('#607D8B', '#607D8B')], max_length=7)),
                ('visibility_type', models.CharField(choices=[('all_friends', 'All Friends'), ('specific_rooms', 'Specific Rooms')], default='all_friends', max_length=20)),
                ('duration_type', models.CharField(choices=[('hour', '1 Hour'), ('day', '1 Day'), ('indefinite', 'Indefinite')], default='indefinite', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rooms', models.ManyToManyField(blank=True, related_name='visible_activities', to='chat.room')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'expires_at'], name='chat_activi_user_id_d92eb6_idx'), models.Index(fields=['expires_at'], name='chat_activi_expires_d982f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActivityPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('color', models.CharField(choices=[('#4CAF50', '#4CAF50'), ('#2196F3', '#2196F3'), ('#9C27B0', '#9C27B0'), ('#FF5722', '#FF5722'), ('#F44336', '#F44336'), ('#FFC107', '#FFC107'), ('#00BCD4', '#00BCD4'), ('#8BC34A', '#8BC34A'), ('#3F51B5', '#3F51B5'), ('#E91E63', '#E91E63'), ('#795548', '#795548'), ('#607D8B', '#607D8B')], max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
