# Generated by Django 5.0 on 2026-04-12 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_activity_activitypreset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activitypreset',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-bumped_at']},
        ),
        migrations.RemoveIndex(
            model_name='activity',
            name='chat_activi_user_id_d92eb6_idx',
        ),
        migrations.RemoveIndex(
            model_name='activity',
            name='chat_activi_expires_d982f9_idx',
        ),
        migrations.RemoveIndex(
            model_name='block',
            name='chat_block_blocker_b7f550_idx',
        ),
        migrations.RemoveIndex(
            model_name='block',
            name='chat_block_blocked_b8c679_idx',
        ),
        migrations.RemoveIndex(
            model_name='friendrequest',
            name='chat_friend_from_us_369900_idx',
        ),
        migrations.RemoveIndex(
            model_name='friendrequest',
            name='chat_friend_to_user_c13507_idx',
        ),
        migrations.RemoveIndex(
            model_name='friendrequest',
            name='chat_friend_status_7d90ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='friendship',
            name='chat_friend_user1_i_023629_idx',
        ),
        migrations.RemoveIndex(
            model_name='friendship',
            name='chat_friend_user2_i_5b6154_idx',
        ),
        migrations.AlterUniqueTogether(
            name='roommember',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='activity',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cdc',
            name='method',
        ),
        migrations.RemoveField(
            model_name='cdc',
            name='partition',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='outbox',
            name='method',
        ),
        migrations.RemoveField(
            model_name='outbox',
            name='partition',
        ),
        migrations.RemoveField(
            model_name='room',
            name='last_message',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='id',
        ),
        migrations.AddField(
            model_name='cdc',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.room'),
        ),
        migrations.AddField(
            model_name='outbox',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='color',
            field=models.CharField(default='#3280b4', max_length=7),
        ),
        migrations.AddField(
            model_name='room',
            name='founder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founded_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='visibility_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='activitypreset',
            name='color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='block',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.room'),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='custom_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', max_length=10),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='status', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='roommember',
            unique_together={('user', 'room')},
        ),
        migrations.AddField(
            model_name='banneduser',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned_users', to='chat.room'),
        ),
        migrations.AddField(
            model_name='banneduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='banneduser',
            unique_together={('user', 'room')},
        ),
    ]
