# Generated by Django 5.0 on 2026-04-12 22:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_dailyscreentime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyscreentime',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
